#!/bin/bash
clear
#--------------------------
# SSH-PLUS
# CANAL TELEGRAM: @SafeCLoudServer
#--------------------------

# - Atualiza Lista/Pacotes/Sistema
dpkg --configure -a
apt update -y && apt upgrade -y
apt install unzip python3 -y

# - Execulta instalador
wget https://raw.githubusercontent.com/juninho472/SafeCloud/main/F2/Plus && chmod 777 Plus && ./Plus
